# config/llm/anthropic.yaml
# Anthropic Claude configuration

provider: anthropic
model: claude-3-5-sonnet-20241022
temperature: 0.0
max_tokens: 4096
timeout: 60
max_retries: 3

anthropic:
  api_key_env: ANTHROPIC_API_KEY
  api_base: null

available_models:
  - claude-3-5-sonnet-20241022
  - claude-3-opus-20240229
  - claude-3-sonnet-20240229
