[run]
branch = true
source = ["src/research_assistant"]
omit = [
    "src/research_assistant/__init__.py",
    "tests/*",
]

[report]
show_missing = true
skip_covered = false
fail_under = 85  # Global minimum coverage threshold
precision = 2

# Module-specific coverage thresholds
[paths]
source = ["src/research_assistant"]


# 👇 custom section read by check_coverage.py
[coverage_thresholds]
"core/schemas.py" = 95
"nodes/" = 85
"tools/" = 80
"graphs/" = 75
"utils/" = 85
