# config/search/default.yaml
# Default search configuration

web:
  enabled: true        # Whether web search is active
  provider: tavily     # Web search provider
  max_results: 3       # Number of web results to load
  use_cache: true
  cache_ttl: 3600
  rate_limit_requests: 10
  rate_limit_window: 60
  timeout: 30
  
  tavily:
    api_key_env: TAVILY_API_KEY
    search_depth: basic  # Options: basic, advanced
    include_answer: false
    include_raw_content: false
    max_results: 3

wikipedia:
  enabled: true
  load_max_docs: 2      # Max number of Wikipedia docs to load
  use_cache: true
  cache_ttl: 7200
  rate_limit_requests: 10
  rate_limit_window: 60
  lang: en
