# config/llm/openai.yaml
# OpenAI LLM configuration

provider: openai
model: gpt-4o
temperature: 0.0
max_tokens: null
timeout: 60
max_retries: 3

# Model-specific settings
openai:
  api_key_env: OPENAI_API_KEY
  organization: null
  api_base: null
  api_version: null

# Available models (for reference)
available_models:
  - gpt-4o
  - gpt-4o-mini
  - gpt-4-turbo
  - gpt-3.5-turbo
